//
// PAOtrainer.JS
// (c) 2014 Eric Knudsen
//

defaultData = [{"card":"2&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"021"},
					{"card":"2&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"023"}, 
					{"card":"2&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"022"},
					{"card":"2&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"024"},
					{"card":"3&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"031"}, 
					{"card":"3&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"033"}, 
					{"card":"3&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"032"},
					{"card":"3&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"034"},
					{"card":"4&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"041"}, 
					{"card":"4&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"043"}, 
					{"card":"4&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"042"},
					{"card":"4&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"044"},
					{"card":"5&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"051"}, 
					{"card":"5&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"053"}, 
					{"card":"5&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"052"},
					{"card":"5&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"054"},
					{"card":"6&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"061"}, 
					{"card":"6&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"063"}, 
					{"card":"6&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"062"},
					{"card":"6&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"064"},
					{"card":"7&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"071"}, 
					{"card":"7&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"073"}, 
					{"card":"7&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"072"},
					{"card":"7&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"074"},
					{"card":"8&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"081"}, 
					{"card":"8&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"083"}, 
					{"card":"8&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"082"},
					{"card":"8&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"084"},
					{"card":"9&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"091"}, 
					{"card":"9&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"093"}, 
					{"card":"9&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"092"},
					{"card":"9&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"094"},
					{"card":"10&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"101"},
					{"card":"10&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"103"},
					{"card":"10&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"102"},
					{"card":"10&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"104"},
					{"card":"J&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"111"}, 
					{"card":"J&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"113"}, 
					{"card":"J&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"112"},
					{"card":"J&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"114"},
					{"card":"Q&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"121"}, 
					{"card":"Q&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"123"}, 
					{"card":"Q&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"122"},
					{"card":"Q&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"124"},
					{"card":"K&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"131"}, 
					{"card":"K&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"133"}, 
					{"card":"K&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"132"},
					{"card":"K&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"134"},
					{"card":"A&diams;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"011"}, 
					{"card":"A&clubs;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"013"}, 
					{"card":"A&hearts;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"012"},
					{"card":"A&spades;", "active":0, "person":"Person", "action":"Action", "object":"Object","img":"014"}];
